name: HES CI/CD Pipeline

on:
  push:
    branches: ["ci-cd"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Make mvnw executable
        run: chmod +x hes/mvnw

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests
        working-directory: hes


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hes-app
          path: hes/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: hes-app

      - name: Deploy to Factory Server 
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }} 
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "*.jar"
          target: "/home/${{ secrets.SERVER_USER }}/hes-app/"

      - name: Restart HES Application
        uses: appleboy/ssh-action@v0.1.7
        with:
           host: ${{ secrets.SERVER_HOST }}
           username: ${{ secrets.SERVER_USER }}
           key: ${{ secrets.SERVER_SSH_KEY }}
           script: |
            

            echo "ðŸ“‚ Navigating to app directory..."
            cd /home/${{ secrets.SERVER_USER }}/hes-app || { echo "âŒ Directory not found"; exit 1; }

            if [[ ! -f hes-0.0.1-SNAPSHOT.jar ]]; then
             echo "âŒ JAR file not found!"
            exit 1
            fi

            echo "ðŸš€ Starting new process with 'prod' profile..."

            # Export environment variables for Spring Boot
            export SPRING_PROFILES_ACTIVE=prod
            export SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }}
            export SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }}
            export SPRING_SECURITY_USER=${{ secrets.SPRING_SECURITY_USER }}
            export SPRING_SECURITY_PASSWORD=${{ secrets.SPRING_SECURITY_PASSWORD }}

            nohup java -jar hes-0.0.1-SNAPSHOT.jar > app.log 2>&1 &

            echo "âœ… Application started."
             
